### ISSUE TITLE
Text to clarify sections and functionality on Effechecka

### ISSUE THREAD

**Issue by mariestuder** [jhpoelen/effechecka#18]
Hi Jorrit -  The descriptions you added to the different sections are very helpful.  The Introduction, Spatial Selector and Taxon Selector sections are clear.  

I think the Checklist section could use some more description.  The opening sentence helps, but can you add something about what the query from the iDigBio specimen record will return?  For example, are the Checklist results (i.e., species listed and occurrence counts) related to the spatial area selected above?  Is there any sense of how "complete" these results are?  Also, are there plans to query other databases in the future? 

Same with the Occurrences section:  These results appear to be from all over the world and not necessarily associated with the Spatial Selector -- although some are (the last set in my query).  Can you please clarify what this query is returning?  Why are there multiple "chunks" of 20 taxa?  Is that significant in any way?

**Comment by jhpoelen** [comment]
@mariestuder thanks for your suggestions. 

I've done two things:

1. update the checklist / occurrence text - please review the text and provide specifics so that we can nail down the verbiage 
1. fix a bug in the GBIF occurrence generator - on first loading, three lists were generated, where only the last one was constrained by area and first taxon constraint. 

Please holler if you have more comments and ideas.
