### ISSUE TITLE
No results returned for place where GBIF does have records

### ISSUE THREAD

**Issue by holmesjtg** [jhpoelen/effechecka#26]
I was trying to see how effechecka would do against a couple of lists that I had come across for species in Gombe National Park (Tanzania). When I ran the following on effechecka, I didn't get any results:

http://www.effechecka.org/#geometry=POLYGON%28%2829.66720581054688%20-4.6243352706081025%2C29.66720581054688%20-4.751624041481169%2C29.6026611328125%20-4.751624041481169%2C29.6026611328125%20-4.6243352706081025%2C29.66720581054688%20-4.6243352706081025%29%29&hasSpatialIssue=false&height=186&lat=-4.687982554733072&limit=20&lng=29.634933471679684&scientificName=Aves& amp;taxonSelector=Aves&traitSelector=&width=94&wktString=ENVELOPE%2829.6026611328125%2C29.66720581054688%2C-4.6243352706081025%2C-4.751624041481169%29&zoom=11

I did a GBIF search on the area and got back 1858 records: http://www.gbif.org/occurrence/download/0001801-151016162008034

**Comment by jhpoelen** [comment]
@holmesjtg thanks for taking effechecka.org for a little test ride. [Your search](http://www.effechecka.org/#geometry=POLYGON%28%2829.66720581054688%20-4.6243352706081025%2C29.66720581054688%20-4.751624041481169%2C29.6026611328125%20-4.751624041481169%2C29.6026611328125%20-4.6243352706081025%2C29.66720581054688%20-4.6243352706081025%29%29&hasSpatialIssue=false&height=186&lat=-4.687982554733072&limit=20&lng=29.634933471679684&scientificName=Aves&taxonSelector=Aves&traitSelector=bodyMass%20%3E%2010%20g%2CbodyMass%20%3C%201.0%20kg&width=94&wktString=ENVELOPE%2829.6026611328125%2C29.66720581054688%2C-4.6243352706081025%2C-4.751624041481169%29&zoom=11) was empty because:

1. the checklists are generated from iDigBio specimen data. iDigBio apparently does not have birds (Aves) with bodyMass > 10g and less than 1.0 kg .
2. the occurrence section is generated from GBIF, however, since you selected to include only birds (Aves) and no birds were present (as far as I can tell) for that area in GBIF . 

Please note that we do have plans to include GBIF data (see #8) in effechecka, we just didn't get to it yet. Also, please note that the occurrence section on effechecka does not take the trait selector (e.g. bodyMass) into account.

Please re-open this issue if you feel that you still had unexpected results.

**Comment by holmesjtg** [comment]
Ah, okay. I didn't realize that GBIF data aren't included in the results yet. Thanks for clarifying.

**Comment by jhpoelen** [comment]
@holmesjtg fyi - effechecka now includes GBIF occurrences (see #8).
