### ISSUE TITLE
EOL save options sometimes don't appear

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/effechecka#31]
Oops, just tried this query: 

http://www.effechecka.org/#geometry=POLYGON%28%28-55.1953125%2070.37785394109227%2C-55.1953125%2046.55886030311719%2C-137.109375%2046.55886030311719%2C-137.109375%2070.37785394109227%2C-55.1953125%2070.37785394109227%29%29&hasSpatialIssue=false&height=272&lat=60.58696734225869&limit=20&lng=-96.15234375&scientificName=Aves&taxonSelector=Aves&traitSelector=&width=466&wktString=ENVELOPE%28-137.109375%2C-55.1953125%2C70.37785394109227%2C46.55886030311719%29&zoom=3

Largish results, 1305 taxa. I got only JSON and csv save options, no EOL taxon IDs or collection option. All options are still appearing for other searches, although, for this one, it was a second or so after the checklist and the first two options appeared that the EOL options arrived:

http://www.effechecka.org/#geometry=POLYGON%28%28-80.595703125%2031.05293398570514%2C-80.595703125%2018.312810846425442%2C-97.822265625%2018.312810846425442%2C-97.822265625%2031.05293398570514%2C-80.595703125%2031.05293398570514%29%29&hasSpatialIssue=false&height=160&lat=24.84656534821976&limit=20&lng=-89.20898437499999&scientificName=Elasmobranchii&taxonSelector=Elasmobranchii&traitSelector=&width=196&wktString=ENVELOPE%28-97.822265625%2C-80.595703125%2C31.05293398570514%2C18.312810846425442%29&zoom=4

![missingsaveoptions](https://cloud.githubusercontent.com/assets/3026567/10696383/73b09e30-7975-11e5-8b5a-a18294df7f7c.jpg)

**Comment by jhpoelen** [comment]
Previously, the "save to eol collection" did not work for checklist with more than 1000 items. The reason was that the underlying api (http://globalnames.org) switches to a more appropriate download mechanism when linking a big list of names: an offline process. 

Now, names are linked in chunks of 200, to allow for a progressive linking in bite sized chunks. 

In addition, a new checklist status is introduce to indicate that the names are being linked. 

@jhammock please re-open if the issue still occurs.

**Comment by jhammock** [comment]
"linking to eol pages..."  sounds good :)
