### ISSUE TITLE
Empty list for this query

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/effechecka#35]
http://www.effechecka.org/#geometry=POLYGON%28%28-78.013916015625%2038.03078569382294%2C-78.013916015625%2039.740986355883564%2C-75.816650390625%2039.740986355883564%2C-75.816650390625%2038.03078569382294%2C-78.013916015625%2038.03078569382294%29%29&height=200&lat=38.89103282648849&limit=20&lng=-76.915283203125&scientificName=Insecta&taxonSelector=Insecta&traitSelector=bodyMass%20%3C%201.0%20kg&width=200&wktString=ENVELOPE%28-78.013916015625%2C-75.816650390625%2C39.740986355883564%2C38.03078569382294%29&zoom=7

(app-20151103140944-0206 on the dashboard)

**Comment by jhpoelen** [comment]
Hey @jhammock - I looked at your query (Insecta near Maryland with bodyMass < 1.0 kg). After removing the bodyMass < 1.0 kg , if found 465 matching insect taxa. I manually checked the species occurring in this list (e.g. _Sigara virginiensis_, _Sigara variabilis_, _Colletes latitarsus_, _Colletes latitarsis_). None of the species I checked has any matching records in the body mass traitbank record that were provided. So, it is very likely that we found a data gap in traitbank's body mass records. 

So, according to what I am seeing, effechecka is producing expected results: no matching records of insects that have a body mass that that is smaller than 1.0 kg. Closing issue.

PS Let me know if you have a more complete set of body mass traits that includes these insects or if you have a way to deal with this creatively: for instance: are there records that provide body mass traits for families, classes etc, so that we can answer questions like: are there any insects heavier than 1.0 kg?

Please comment on this issue if you

**Comment by jhpoelen** [comment]
PS here's the query without the body mass : http://www.effechecka.org/#geometry=POLYGON%28%28-78.013916015625%2038.03078569382294%2C-78.013916015625%2039.740986355883564%2C-75.816650390625%2039.740986355883564%2C-75.816650390625%2038.03078569382294%2C-78.013916015625%2038.03078569382294%29%29&height=200&lat=38.89103282648849&limit=20&lng=-76.915283203125&scientificName=Insecta&taxonSelector=Insecta&traitSelector=&width=200&wktString=ENVELOPE%28-78.013916015625%2C-75.816650390625%2C39.740986355883564%2C38.03078569382294%29&zoom=7

**Comment by jhammock** [comment]
oops, my mistake; I heard Michele's report and leapt to conclusions. But it raises a good TraitBank point. We could do better with body mass for invertebrates; I'll poke around...

**Comment by jhpoelen** [comment]
I've created a placeholder issue to document this here: #38 .
