### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by mxweber** [jhpoelen/effechecka#36]
Everything seems to end up as "killed". I am not sure what "back to master" is supposed to do. I was imagining something like the master query… but I get an error and blank page.

**Comment by jhpoelen** [comment]
@mxweber do you happen to have the query that caused this to happen? You can just copy-paste the url on the top of your browser windows (see #35 for example).

**Comment by mxweber** [comment]
I could not find the original version. I tried running a similar query. It was something like this:
http://www.effechecka.org/#geometry=POLYGON%28%28-89.12109375%208.928487062665504%2C-89.12109375%2029.6880527498568%2C-66.97265625%2029.6880527498568%2C-66.97265625%208.928487062665504%2C-89.12109375%208.928487062665504%29%29&height=126&lat=19.642587534013032&limit=20&lng=-78.046875&scientificName=scleractinia&taxonSelector=scleractinia&traitSelector=&width=126&wktString=ENVELOPE%28-89.12109375%2C-66.97265625%2C29.6880527498568%2C8.928487062665504%29&zoom=3

**Comment by jhpoelen** [comment]
Thanks for sharing your search url. Just checked it and found that there's two issues: (1) a known stability issue (working on that) - I think at busy time the server runs out of resources and starts to "freak out" (2) the taxon name that you provided "scleractinia", didn't give you any results because the proper name is "Scleractinia" (notice the capital S). I'll try to address (2) by automatically capitalizing the first word of the taxon. Also, I'll poke around to figure out how to reproduce and fix (1).

by the way: the capitalized version of your search produced a list of 67 items. You can see the results in the attached checklist.txt or here: http://www.effechecka.org/#geometry=POLYGON%28%28-89.12109375%208.928487062665504%2C-89.12109375%2029.6880527498568%2C-66.97265625%2029.6880527498568%2C-66.97265625%208.928487062665504%2C-89.12109375%208.928487062665504%29%29&height=126&lat=19.642587534013032&limit=20&lng=-78.046875&scientificName=Scleractinia&taxonSelector=Scleractinia&traitSelector=&width=126&wktString=ENVELOPE%28-89.12109375%2C-66.97265625%2C29.6880527498568%2C8.928487062665504%29&zoom=3

[checklist.txt](https://github.com/jhpoelen/effechecka/files/26717/checklist.txt)

**Comment by jhpoelen** [comment]
I've implemented (2): now when you enter a lowercase taxon name (e.g. "scleractinia"), effechecka will put "Scleractinia" in the list. Haven't been able to reproduce the performance issue now. Have opened a separate issue for that here: #37. 

If the fix for (2) is not working as expected please comment on this issue. Thanks!
