### ISSUE TITLE
Failed to write EOL collection of 10 items

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/effechecka#44]
Query: driver-20160225154809-0038

I tried to write the first 30 taxa to EOL at first, then tried 10 a couple of times, no luck with that either.

**Comment by jhpoelen** [comment]
Thanks for reporting this @jhammock . Turned out that the root cause was a failing workaround for the older version of the eol write api . . . (related to CORS, https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS). EOL wapi now apparently supports CORS (yay to @JRice et al.) and made the workaround blow up. So, the fix was to remove the workaround and use the wapi directly. 

Here's a collection I created just now: http://eol.org/collections/122315 . 

Hope this resolved the issue for you. If not, do please let me know.
