### ISSUE TITLE
api.effechecka.org 502 Bad Gateway

### ISSUE THREAD

**Issue by eliagbayani** [jhpoelen/effechecka#53]
from: tail -f /var/log/nginx/error.log

failed (111: Connection refused) while connecting to upstream, client: 10.5.145.142, server: apihack-c18.idigbio.org

**Comment by eliagbayani** [comment]
Was able to restart Nginx.
sudo service nginx reload|restart|force-reload
Nginx is actually running. The gateway problem I guess is the communication between back-end computers. One for the sysadmin I suppose.

**Comment by jhpoelen** [comment]
@eliagbayani thanks for sharing. It sounds like you've eliminated nginx as root cause for the outage. Unless you migrated services to the 11-node cluster created by @godfoder and @mjcollin, the current system does not rely on any of the other iDigBio infrastructure. Following a process of elimination using https://github.com/gimmefreshdata/freshdata/wiki/architecture this leaves services like marathon, mesos and cassandra to be looked at. Curious to how you are going to resolve this.

PS I would suggest to put notices on both effechecka and gimmefreshdata front-ends, indicating that the system is down and provide contact information.

**Comment by eliagbayani** [comment]
Okay, will proceed and will give feedback soon.

**Comment by eliagbayani** [comment]
Hi Jorrit, SOS I need some help here.
I was able to restart cassandra, zookeeper and mesos is already running. BUT I can't seem to restart marathon:

cassandra:
int@xxx:~/apache-cassandra-2.1.15$ sudo /etc/init.d/cassandra restart
  * Restarting Cassandra cassandra [ OK ] 

zookeeper:
int@xxx:/usr/share/zookeeper$ sudo bin/zkServer.sh start
JMX enabled by default
Using config: /etc/zookeeper/conf/zoo.cfg
Starting zookeeper ... STARTED

* I can't find where to run marathon startup:
--master zk://apihack-c18.idigbio.org:2181/mesos --zk zk://apihack-c18.idigbio.org:2181/marathon --http_port 8082 --http_address localhost

The only marathon folder I'm seeing from server is this one:
/etc/marathon

**Comment by jhpoelen** [comment]
On ubuntu, ```service``` is used to start, stop or check status of background processes, just like you discovered with nginx. Same idea should work with marathon, mesos, cassandra etc. I actually did do some testing a while ago to make sure that all service come up after a reboot (see https://github.com/jhpoelen/effechecka/issues/13).

Hope this helps.

**Comment by eliagbayani** [comment]
Hi Jorrit, I understand thanks. But do you remember how you might have ran/started Marathon. Just to cut short the 'discovery/exploratory' phase on my part since this is just how to run the server. Thanks.

**Comment by mjcollin** [comment]
@godfoder and I will pick this up and get the services running again. Thanks for your initial debugging @eliagbayani and @jhpoelen.

**Comment by eliagbayani** [comment]
Thanks much @mjcollin and @godfoder @jhpoelen - service is back.
